
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['^ *# ']
  Exclude:
    - countries.gemspec

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - Rakefile
    - 'lib/countries/tasks/*'

Style/CaseEquality:
  Exclude:
    - 'lib/countries/country/finder_methods.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'spec/thread_safety_spec.rb'

Naming/MethodName:
  Exclude:
    - 'lib/countries/country/class_methods.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/perf_spec.rb'

Metrics/ClassLength:
  Max: 130

Metrics/AbcSize:
  Exclude:
    - 'lib/countries/sources/cldr/*'